### PR TITLE
Big Sur: Fixing Multiple Selection

### LINKED ISSUE #753: BigSur: Multiple Selection Glitch
### Details:
1. Log into your account
2. Command + Click multiple consecutive notes in your Notes List

As a result, each row will render with a rounded squared background. We'd expect consecutive rectangles not to display rounded corners (it should look like a single big rectangle!)

### PR DESCRIPTION
**Pull request by jleandroperez**
### Fix
In this PR we're adjusting the way TableRowView renders whenever you're selecting multiple rows.

### Test
1. Launch Simplenote
2. Command click multiple notes

- [x] Verify the selection looks super in Catalina (should be like a big square!)
- [ ] Verify the selection looks **epic** in Big Sur (single big square, rounded corners only at the top / bottom)

@eshurakov You game for **yet another PR?**
Closes #753

Thank youuu!!

### Release
`RELEASE-NOTES.txt` was updated in dbcdc61 with:

> Fixed a bug that affected Multiple Selection in Big Sur #753

### Screenshots

Before|Now
-|-
Screen Shot 2020-12-11 at 7 00 04 PM|Screen Shot 2020-12-11 at 7 05 07 PM

### CODE REVIEW

File: Simplenote/NSBezierPath+Simplenote.swift [hunk 1]
```diff
@@ -0,0 +1,50 @@
+import Foundation
+
+
+// MARK: - NSBezierPath + Simplenote
+//
+extension NSBezierPath {
+
+    /// Initializes a Bezier Path that only renders the specified corners as rounded
+    ///
+    convenience init(roundedRect rect: NSRect, byRoundingCorners corners: RectCorner, radius: CGFloat) {
```
Comment (eshurakov) [inline Simplenote/NSBezierPath+Simplenote.swift:10]: Oh, you had to create it yourself. iOS provides this out of the box 🚀

**Review by eshurakov — APPROVED** [review]
Checked only on Catalina. Looks great 👍 

:shipit:

File: Simplenote/NSBezierPath+Simplenote.swift (hunk 1 above)
Comment (jleandroperez) [reply Simplenote/NSBezierPath+Simplenote.swift:10]: Yup... that's AppKit!! 🔥

**Comment by jleandroperez** [comment]
Thank you for reviewing this one sir!!
