### PR TITLE
Interlink References

### LINKED ISSUE #663: Interlinking
### Tasks:
- [x] New **Copy Internal Link** Editor Action
- [x] New **Copy Internal Link** List Action
- [x] Interlinks should always get linkified
- [x] Clicking over an Internal Link should push the Target Note onscreen
- [x] Markdown Preview Interlink Support
- [x] Markdown Preview Highlight Colors
- [x] Inline Lookup Mechanism
- [ ] References UI

### Inline Lookup Mechanism
- Filtering Mechanism
  - [x] Backgrounding
  - [x] Invalidate previous search OPs
  - [x] Not Deleted
- Geometry
  - [x] Display below the keyword's first character!
  - [x] Prevent horizontal clipping (Screen Overflow)
  - [x] Prevent vertical clipping (Fullscreen)
  - [x] Relocate on Multiline?
- Interface
  - [x] Rounded Corners
  - [x] Cursor = Hand!
- Display / Hide Mechanism
  - [x] Dismiss when there are no keywords
  - [x] Dismiss on: [.mouseClick, .scrollWheel]
  - [x] Allow circular references
- User Input
  - [x] Review: Architecture. NSWindowController Ownership
  - [x] Arrows
  - [x] Interlink Insertion
- Phase II
  - [x] Display only when there are search results
  - [x] Dismiss when there are no results
  - [x] Discard notes that don't contain the keyword in the title
  - [x] BUG: Delete > Ctrl Z > Might result in AutocompleteWindow and incorrect cursor location. Main hook: KeyDown?
  - [x] Review Remote Update Scenarios
  - [x] Review performance in large accounts
  - [ ] Adapt window size to Content!
  - [ ] Display up to 5 autocomplete rows

### Mockups:
blueprint_macos

### PR DESCRIPTION
**Pull request by jleandroperez**
### Details:
- Rebuilds the Metrics UI, based on NSTableView
- Implements new NSTableViewCell subclasses: `[MetricTableViewCell, ReferenceTableViewCell, SeparatorTableViewCell]`
- Metrics: We're now displaying inbound note references

@eshurakov Mind taking a look at this one Evgeny?
Thank youuu!

Ref. #663 

### Test: Multiple Selection
1. Log into your account!
2. Right click over **Note A** in your notes list: click over `Copy Internal Link`
3. Click over **Note B** and paste the contents of your clipboard
4. CMD + Click over **Note A** + **Note B** in your list
5. Click over the top right `( i )` icon

- [x] Verify only 5 rows show up:
- [x] Verify only `Words` and `Characters` are populated
- [x] Verify that editing either `Note A` or `Note B` in a secondary device (simplenote.com on the web works!) causes the UI to refresh

### Test: Single Selection
1. Log into your account!
2. Right click over **Note A** in your notes list: click over `Copy Internal Link`
3. Paste the contents of your clipboard on **at least** 4 notes (so that 4 notes reference back to Note A!)
4. Click over **Note A**
5. Click over the top right `( i )` icon

- [x] Verify that all of the inbound links (References!) you pasted in step 3 show up at the bottom of the Metrics UI
- [x] Verify that you can scroll **all of the contents** of the Metrics UI (every single row should move!)

### Release
These changes do not require release notes.

---

### Screenshots
Screen Shot 2020-10-21 at 15 22 11

Screen Shot 2020-10-21 at 15 22 24

### CODE REVIEW

File: Simplenote/MetricsViewController.swift [hunk 1]
```diff
@@ -7,41 +7,52 @@ import SimplenoteFoundation
...
+    /// ResultsController: In charge of CoreData Queries!
     ///
-    private var presentingPopover: NSPopover? {
-        didSet {
-            refreshStyle()
-        }
-    }
+    private lazy var resultsController = ResultsController<Note>(viewContext: mainContext, sortedBy: [
+        NSSortDescriptor(keyPath: \Note.content, ascending: true)
+    ])
```
Comment (eshurakov) [inline Simplenote/MetricsViewController.swift:51]: Just a thought, should the order match the order that is set in the list? (last modified / alphabetically)

File: Simplenote/MetricsViewController.swift [hunk 2]
```diff
@@ -82,16 +89,22 @@ class MetricsViewController: NSViewController {
...
         observer.delegate = self
     }
+
+    func setupResultsControllerIfNeeded() {
+        guard mustSetupResultsController, let plainInterlink = notes.first?.plainInterlink else {
+            return
+        }
+
+        resultsController.predicate = NSPredicate.predicateForNotes(exactMatch: plainInterlink)
+        try? resultsController.performFetch()
```
Comment (eshurakov) [inline Simplenote/MetricsViewController.swift:106]: We probably need to setup a listener here and update the table? 🤔

**Review by eshurakov — COMMENTED** [review]
Looks great! 

Nitpicking: I noticed that last modified date is formatted quite differently. Wonder if we want to make it more similar and for example drop time in the list but keep the date format the same.

Also we use different words for the same thing: "Date Updated", "Modified", "Last Modified".

Screenshot 2020-10-22 at 07 37 05

File: Simplenote/MetricsViewController.swift [hunk 3]
```diff
@@ -138,21 +143,186 @@ private extension MetricsViewController {
...
-        wordsDetailsLabel.stringValue = String(metrics.numberOfWords)
-        charsDetailsLabel.stringValue = String(metrics.numberOfChars)
+            .metric(title: NSLocalizedString("Created", comment: "Note Creation Date"),
+                    value: metrics.creationDate),
+
+            .metric(title: NSLocalizedString("Words", comment: "Number of words in the note"),
+                    value: String(metrics.numberOfWords)),
+
+            .metric(title: NSLocalizedString("Characters", comment: "Number of characters in the note"),
+                    value: String(metrics.numberOfChars))
```
Comment (eshurakov) [inline Simplenote/MetricsViewController.swift]: Maybe we can format numbers using a decimal formatter. If the number is big, it looks better and easier to read with delimiters.

Comment (jleandroperez) [reply Simplenote/MetricsViewController.swift]: Awesome idea, done!! thank you!

File: Simplenote/MetricsViewController.swift (hunk 2 above)
Comment (jleandroperez) [reply Simplenote/MetricsViewController.swift:106]: 🤦  I totally forgot about that. Done, thank you!!

File: Simplenote/MetricsViewController.swift (hunk 1 above)
Comment (jleandroperez) [reply Simplenote/MetricsViewController.swift:51]: Let's skip that one and keep it alpha, for a bit at least! 

We've got missing sort options available in other platforms, it'd be neat to address that first.

**Comment by jleandroperez** [comment]
@eshurakov Q for you!!

```
noticed that last modified date is formatted quite differently. Wonder if we want to make it more similar and for example drop time in the list but keep the date format the same.
```

I can't find where else is the last modified date showing up. Is it possible that was iOS?

Regarding the wording change, I'd stick to the wording in the mockups if you don't mind! It feels a bit redundant to include the word `date` (when the text on the right hand is a date).

Other than that, ready for another peek sir! thaaank you!!

**Comment by eshurakov** [comment]
> I can't find where else is the last modified date showing up. Is it possible that was iOS?

Sorry @jleandroperez, what I meant is that in the note information popover `modified` date is formatted as "21 Oct 2020 at 10:10" and `last modified` date for each reference is formatted as "21/10/2020".
So I was wondering if it makes sense to use format that is closer to each other. For example, format the date in second case as "21 Oct 2020" without time.

**Review by eshurakov — APPROVED** [review]
🚀 
🚢 :shipit:

**Comment by jleandroperez** [comment]
Ahhhhh thank you @eshurakov !!! totally missed that. Love the idea, updated!

🔥
