### PR TITLE
Fixing Main Window Autosave mechanism

### LINKED ISSUE #629: App Does Not "Remember" Window Position
### Expected
When a user closes the app it should reopen again as the same size and position on the screen. 

### Observed
The app remembers it's size, but always opens in the middle of the screen, no matter where it was previously. 

Make|Model|macOS Version|App Version
-|-|-|-
SYSTEM_MAKE|SYSTEM_MODEL|MACOS_VERSION|APP_VERSION
Mac| Mac| Mojave 10.14.6| Simplenote 1.12

Unable to reproduce on Catalina 10.15.5

Reported:
#3185202-zen

### PR DESCRIPTION
**Pull request by jleandroperez**
### Fix
In this PR we're fixing the main NSWindow's position autosave mechanism. 

Workaround involves simply setting (another) autosavename after setting the RootViewController.
[Ref. here!](https://developer.apple.com/forums/thread/23453)

@emilylaguna Emily!! May I trouble you yet again?
Thanks in advance!!
Closes #629

### Test
1. Launch Simplenote in High Sierra (OR) Mojave
2. Log into your account
3. Resize / relocate your window
4. Quit the app
5. Relaunch

- [ ] Verify the app remembers its last position

### Release
`RELEASE-NOTES.txt` was updated in cab427d with: 

> Fixed a bug that prevented the main Window from restoring its last location

### CODE REVIEW

File: Simplenote/NSWindowFrameAutosaveName+Simplenote.swift [hunk 1]
```diff
@@ -0,0 +1,13 @@
...
+
+// MARK: - NSWindow.FrameAutosaveName
+//
+extension NSWindow.FrameAutosaveName {
+
+    /// Main Window Autosave Name
+    ///
+    static var mainWindow: NSWindow.FrameAutosaveName {
+        "SimplenoteMainWindow"
+    }
```
Comment (emilylaguna) [inline Simplenote/NSWindowFrameAutosaveName+Simplenote.swift:12]: What about simplifying this down to
```suggestion
    static var mainWindow: NSWindow.FrameAutosaveName = "SimplenoteMainWindow"
```

Comment (jleandroperez) [reply Simplenote/NSWindowFrameAutosaveName+Simplenote.swift:12]: Thank you!!

**Comment by jleandroperez** [comment]
Thank you Emily!!!
