### PR TITLE
Notes Exporter

### LINKED ISSUE #294: Add the capability to export and import all notes
The electron variant allows you to export all notes at once from the File menu. Add that capability to this variant.

#### Steps to reproduce
1. Open the app
2. Try to export all notes

#### What I expected

A menu option to export all notes

#### What happened instead

Can't export all notes

#### Simplenote version

Simplenote 1.4.0

#### macOS version

macOS 10.14.2

### PR DESCRIPTION
**Pull request by jleandroperez**
### Details:
This PR implements a new feature, which gives users the ability to export **the local state of every note they've got** to macOS's filesystem.

This feature isn't meant for day to day usage. We're locking it down under an App URL, for the time being.

**NOTE:** You might need to uninstall AppStore / Betas for the Xcode tests to succeed!

Closes #294

### Scenario: Hidden Menu
1. Launch Simplenote
2. Open the macOS System Menu
3. Click over the `Simplenote` Item

- [x] Verify **Export Everything** is not visible

### Scenario: Unlock URL
1. Launch Simplenote
2. Open macOS's Spotlight and enter this URL: `simplenote://export`
3. Bring Simplenote to the focus
4. Open the macOS System Menu
5. Click over the `Simplenote` Item
6. Click over `Export Everything`

- [x] Verify all of your notes are stored at a given location

### CODE REVIEW

File: Simplenote/SPExporter.swift [hunk 1]
```diff
@@ -0,0 +1,88 @@
...
+        return allEntities.compactMap {
+            $0 as? Note
+        }
+    }
+
+    /// Returns the (target) filename for a given note
+    ///
+    func filename(for note: Note) -> String {
+        let prefix = note.deleted ? Settings.trashedPrefix : Settings.regularPrefix
+        return prefix + "-" + note.simperiumKey.prefix(Settings.hashMaxLenght) + Settings.pathExtension
```
Comment (bummytime) [inline Simplenote/SPExporter.swift]:
```suggestion
        return prefix + "-" + note.simperiumKey.prefix(Settings.hashMaxLenght) + "." + Settings.pathExtension
```

Comment (jleandroperez) [reply Simplenote/SPExporter.swift]: ARGH I can't believe I missed this, thank you Matt!!

**Comment by jleandroperez** [comment]
Thank you for reviewing this one @bummytime !!!
